# fly.toml app configuration file generated for review-ssh on 2023-12-06T21:02:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "review-ssh"
primary_region = "atl"

[build]

[http_service]
  internal_port = 3456
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 3456
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 22

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
