Output account.gif
Set Height 900
Set Padding 32

Type "go run ../main.go"
Enter
Sleep 2s
Down
Sleep 1s

# Attempt sign up with existing email
Enter
Sleep 1s
Type "Pete Fish"
Down
Type "pete@fish.net"
Down
Type "legitpassword"
Down
Type "legitpassword"
Down
Enter
Sleep 2s

Escape
Sleep 1s
Up
Sleep 1s

# Sign in
Enter
Sleep 1s
Type "pete@fish.net"
Down
Type "legitpassword"
Down
Sleep 1s
Enter
Sleep 1s

# Exit
Type "q"
Sleep 1s
Enter

